<?php
/**
 * Charge
 *
 * PHP version 5
 *
 * @category Class
 * @package  zipMoney
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace zipMoney\Model;

use \ArrayAccess;

/**
 * Charge Class Doc Comment
 *
 * @category    Class
 * @package     zipMoney
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Charge implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Charge';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'reference' => 'string',
        'order' => '\zipMoney\Model\Order',
        'state' => 'string',
        'authorised_amount' => 'float',
        'captured_amount' => 'float',
        'refunded_amount' => 'float',
        'created_date' => '\DateTime',
        'state_changes' => '\zipMoney\Model\ChargeStateChanges[]',
        'metadata' => 'object',
        'customer_id' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'reference' => 'reference',
        'order' => 'order',
        'state' => 'state',
        'authorised_amount' => 'authorised_amount',
        'captured_amount' => 'captured_amount',
        'refunded_amount' => 'refunded_amount',
        'created_date' => 'created_date',
        'state_changes' => 'state_changes',
        'metadata' => 'metadata',
        'customer_id' => 'customer_id'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'reference' => 'setReference',
        'order' => 'setOrder',
        'state' => 'setState',
        'authorised_amount' => 'setAuthorisedAmount',
        'captured_amount' => 'setCapturedAmount',
        'refunded_amount' => 'setRefundedAmount',
        'created_date' => 'setCreatedDate',
        'state_changes' => 'setStateChanges',
        'metadata' => 'setMetadata',
        'customer_id' => 'setCustomerId'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'reference' => 'getReference',
        'order' => 'getOrder',
        'state' => 'getState',
        'authorised_amount' => 'getAuthorisedAmount',
        'captured_amount' => 'getCapturedAmount',
        'refunded_amount' => 'getRefundedAmount',
        'created_date' => 'getCreatedDate',
        'state_changes' => 'getStateChanges',
        'metadata' => 'getMetadata',
        'customer_id' => 'getCustomerId'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const STATE_AUTHORISED = 'authorised';
    const STATE_CAPTURED = 'captured';
    const STATE_CANCELLED = 'cancelled';
    const STATE_REFUNDED = 'refunded';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_AUTHORISED,
            self::STATE_CAPTURED,
            self::STATE_CANCELLED,
            self::STATE_REFUNDED,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['reference'] = isset($data['reference']) ? $data['reference'] : null;
        $this->container['order'] = isset($data['order']) ? $data['order'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['authorised_amount'] = isset($data['authorised_amount']) ? $data['authorised_amount'] : null;
        $this->container['captured_amount'] = isset($data['captured_amount']) ? $data['captured_amount'] : null;
        $this->container['refunded_amount'] = isset($data['refunded_amount']) ? $data['refunded_amount'] : null;
        $this->container['created_date'] = isset($data['created_date']) ? $data['created_date'] : null;
        $this->container['state_changes'] = isset($data['state_changes']) ? $data['state_changes'] : null;
        $this->container['metadata'] = isset($data['metadata']) ? $data['metadata'] : null;
        $this->container['customer_id'] = isset($data['customer_id']) ? $data['customer_id'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['id'] === null) {
            $invalid_properties[] = "'id' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalid_properties[] = "'state' can't be null";
        }
        $allowed_values = ["authorised", "captured", "cancelled", "refunded"];
        if (!in_array($this->container['state'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'state', must be one of 'authorised', 'captured', 'cancelled', 'refunded'.";
        }

        if (!is_null($this->container['authorised_amount']) && ($this->container['authorised_amount'] < 0)) {
            $invalid_properties[] = "invalid value for 'authorised_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['captured_amount']) && ($this->container['captured_amount'] < 0)) {
            $invalid_properties[] = "invalid value for 'captured_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['refunded_amount']) && ($this->container['refunded_amount'] < 0)) {
            $invalid_properties[] = "invalid value for 'refunded_amount', must be bigger than or equal to 0.";
        }

        if ($this->container['created_date'] === null) {
            $invalid_properties[] = "'created_date' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['id'] === null) {
            return false;
        }
        if ($this->container['state'] === null) {
            return false;
        }
        $allowed_values = ["authorised", "captured", "cancelled", "refunded"];
        if (!in_array($this->container['state'], $allowed_values)) {
            return false;
        }
        if ($this->container['authorised_amount'] < 0) {
            return false;
        }
        if ($this->container['captured_amount'] < 0) {
            return false;
        }
        if ($this->container['refunded_amount'] < 0) {
            return false;
        }
        if ($this->container['created_date'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets reference
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     * @param string $reference
     * @return $this
     */
    public function setReference($reference)
    {
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets order
     * @return \zipMoney\Model\Order
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     * @param \zipMoney\Model\Order $order
     * @return $this
     */
    public function setOrder($order)
    {
        $this->container['order'] = $order;

        return $this;
    }

    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     * @param string $state
     * @return $this
     */
    public function setState($state)
    {
        $allowed_values = array('authorised', 'captured', 'cancelled', 'refunded');
        if ((!in_array($state, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'state', must be one of 'authorised', 'captured', 'cancelled', 'refunded'");
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets authorised_amount
     * @return float
     */
    public function getAuthorisedAmount()
    {
        return $this->container['authorised_amount'];
    }

    /**
     * Sets authorised_amount
     * @param float $authorised_amount
     * @return $this
     */
    public function setAuthorisedAmount($authorised_amount)
    {

        if (!is_null($authorised_amount) && ($authorised_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $authorised_amount when calling Charge., must be bigger than or equal to 0.');
        }

        $this->container['authorised_amount'] = $authorised_amount;

        return $this;
    }

    /**
     * Gets captured_amount
     * @return float
     */
    public function getCapturedAmount()
    {
        return $this->container['captured_amount'];
    }

    /**
     * Sets captured_amount
     * @param float $captured_amount
     * @return $this
     */
    public function setCapturedAmount($captured_amount)
    {

        if (!is_null($captured_amount) && ($captured_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $captured_amount when calling Charge., must be bigger than or equal to 0.');
        }

        $this->container['captured_amount'] = $captured_amount;

        return $this;
    }

    /**
     * Gets refunded_amount
     * @return float
     */
    public function getRefundedAmount()
    {
        return $this->container['refunded_amount'];
    }

    /**
     * Sets refunded_amount
     * @param float $refunded_amount The amount of the charge that has been refunded
     * @return $this
     */
    public function setRefundedAmount($refunded_amount)
    {

        if (!is_null($refunded_amount) && ($refunded_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $refunded_amount when calling Charge., must be bigger than or equal to 0.');
        }

        $this->container['refunded_amount'] = $refunded_amount;

        return $this;
    }

    /**
     * Gets created_date
     * @return \DateTime
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     * @param \DateTime $created_date
     * @return $this
     */
    public function setCreatedDate($created_date)
    {
        $this->container['created_date'] = $created_date;

        return $this;
    }

    /**
     * Gets state_changes
     * @return \zipMoney\Model\ChargeStateChanges[]
     */
    public function getStateChanges()
    {
        return $this->container['state_changes'];
    }

    /**
     * Sets state_changes
     * @param \zipMoney\Model\ChargeStateChanges[] $state_changes State changes
     * @return $this
     */
    public function setStateChanges($state_changes)
    {
        $this->container['state_changes'] = $state_changes;

        return $this;
    }

    /**
     * Gets metadata
     * @return object
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     * @param object $metadata
     * @return $this
     */
    public function setMetadata($metadata)
    {
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets customer_id
     * @return string
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     * @param string $customer_id
     * @return $this
     */
    public function setCustomerId($customer_id)
    {
        $this->container['customer_id'] = $customer_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\zipMoney\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\zipMoney\ObjectSerializer::sanitizeForSerialization($this));
    }
}


