<?php
/**
 * AddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  zipMoney
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace zipMoney;

/**
 * AddressTest Class Doc Comment
 *
 * @category    Class */
// * @description The address object
/**
 * @package     zipMoney
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Address"
     */
    public function testAddress()
    {

    }

    /**
     * Test attribute "line1"
     */
    public function testPropertyLine1()
    {

    }

    /**
     * Test attribute "line2"
     */
    public function testPropertyLine2()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {

    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

}
