<?php
/**
 * CreateChargeRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  zipMoney
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace zipMoney;

/**
 * CreateChargeRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateChargeRequest
/**
 * @package     zipMoney
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateChargeRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateChargeRequest"
     */
    public function testCreateChargeRequest()
    {

    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {

    }

    /**
     * Test attribute "authority"
     */
    public function testPropertyAuthority()
    {

    }

    /**
     * Test attribute "capture"
     */
    public function testPropertyCapture()
    {

    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {

    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {

    }

}
