<?php
/**
 * OrderItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  zipMoney
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace zipMoney;

/**
 * OrderItemTest Class Doc Comment
 *
 * @category    Class */
// * @description OrderItem
/**
 * @package     zipMoney
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "OrderItem"
     */
    public function testOrderItem()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "image_uri"
     */
    public function testPropertyImageUri()
    {

    }

    /**
     * Test attribute "item_uri"
     */
    public function testPropertyItemUri()
    {

    }

    /**
     * Test attribute "product_code"
     */
    public function testPropertyProductCode()
    {

    }

}
