<?php
/**
 * ShopperStatisticsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  zipMoney
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace zipMoney;

/**
 * ShopperStatisticsTest Class Doc Comment
 *
 * @category    Class */
// * @description Statistics relating to the shopper
/**
 * @package     zipMoney
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShopperStatisticsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ShopperStatistics"
     */
    public function testShopperStatistics()
    {

    }

    /**
     * Test attribute "account_created"
     */
    public function testPropertyAccountCreated()
    {

    }

    /**
     * Test attribute "sales_total_count"
     */
    public function testPropertySalesTotalCount()
    {

    }

    /**
     * Test attribute "sales_total_amount"
     */
    public function testPropertySalesTotalAmount()
    {

    }

    /**
     * Test attribute "sales_avg_amount"
     */
    public function testPropertySalesAvgAmount()
    {

    }

    /**
     * Test attribute "sales_max_amount"
     */
    public function testPropertySalesMaxAmount()
    {

    }

    /**
     * Test attribute "refunds_total_amount"
     */
    public function testPropertyRefundsTotalAmount()
    {

    }

    /**
     * Test attribute "previous_chargeback"
     */
    public function testPropertyPreviousChargeback()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "last_login"
     */
    public function testPropertyLastLogin()
    {

    }

}
